spring.application.name=SIDOC

# Perfil: Railway lo define con variable SPRING_PROFILES_ACTIVE=prod (o lo que quieras)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Puerto: Railway expone PORT
server.port=${PORT:8080}

# =========================
# DB (por variables de entorno)
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/sidoc?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}

# =========================
# FTP (por variables de entorno)
# =========================
sidoc.ftp.host=${FTP_HOST:127.0.0.1}
sidoc.ftp.port=${FTP_PORT:21}
sidoc.ftp.user=${FTP_USER:user}
sidoc.ftp.password=${FTP_PASSWORD:password}
sidoc.ftp.passive=${FTP_PASSIVE:true}

# =========================
# RUTAS FTP (si cambian por ambiente, tambien por env vars)
# =========================
sidoc.ruta.archivos=${FTP_RUTA_ARCHIVOS:/Reportes-Doctrina/manuales/archivos/}
sidoc.ruta.portadas=${FTP_RUTA_PORTADAS:/Reportes-Doctrina/manuales/portadas/}

# =========================
# MULTIPART
# =========================
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:512MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:512MB}

# =========================
# APIs (SIEMPRE por env vars) solo se usan las de OpenAI
# =========================
openai.api.key=${OPENAI_API_KEY:}
openai.api.key2=${OPENAI_API_KEY2:}

# (Opcional) logs
logging.level.com.zaxxer.hikari=${HIKARI_LOG_LEVEL:INFO}



# Logging
spring.security.oauth2.resourceserver.jwt.issuer-uri=${ISSUER_URI:}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWKS_URI:}
app.cors.allowed-origins=${ALLOWED_ORIGINS:}