-- ===============================
-- CATALOGO DE FASES
-- ===============================
INSERT ALL
 INTO DMPHS_FASES (DMPH_ID, DMPH_CODIGO, DMPH_NOMBRE_FASE, DMPH_ESTADO) VALUES (1, 1, 'Investigación', 1)
 INTO DMPHS_FASES (DMPH_ID, DMPH_CODIGO, DMPH_NOMBRE_FASE, DMPH_ESTADO) VALUES (2, 2, 'Experimentación', 1)
 INTO DMPHS_FASES (DMPH_ID, DMPH_CODIGO, DMPH_NOMBRE_FASE, DMPH_ESTADO) VALUES (3, 3, 'Edición', 1)
 INTO DMPHS_FASES (DMPH_ID, DMPH_CODIGO, DMPH_NOMBRE_FASE, DMPH_ESTADO) VALUES (4, 4, 'Nota de Aula', 1)
SELECT * FROM DUAL;

-- ===============================
-- CATALOGO DE CATEGORÍAS
-- ===============================
INSERT ALL
 INTO DCCAT_CATEGORIAS (DCCA_ID, DCCA_NOMBRE) VALUES (1,'ARMA')
 INTO DCCAT_CATEGORIAS (DCCA_ID, DCCA_NOMBRE) VALUES (2,'SERVICIO')
 INTO DCCAT_CATEGORIAS (DCCA_ID, DCCA_NOMBRE) VALUES (3,'ESPECIALISTA')
 INTO DCCAT_CATEGORIAS (DCCA_ID, DCCA_NOMBRE) VALUES (4,'VARIOS')
 INTO DCCAT_CATEGORIAS (DCCA_ID, DCCA_NOMBRE) VALUES (5,'ÚNICA DOCTRINA MILITAR CONJUNTA')
 INTO DCCAT_CATEGORIAS (DCCA_ID, DCCA_NOMBRE) VALUES (6,'ÚNICA LITERATURA MILITAR')
 INTO DCCAT_CATEGORIAS (DCCA_ID, DCCA_NOMBRE) VALUES (7,'ÚNICA DOCUMENTOS DE INVESTIGACIÓN')
 INTO DCCAT_CATEGORIAS (DCCA_ID, DCCA_NOMBRE) VALUES (8,'LEYES')
 INTO DCCAT_CATEGORIAS (DCCA_ID, DCCA_NOMBRE) VALUES (9,'REGLAMENTOS')
 INTO DCCAT_CATEGORIAS (DCCA_ID, DCCA_NOMBRE) VALUES (10,'COLECCIÓN DEL EJÉRCITO')
 INTO DCCAT_CATEGORIAS (DCCA_ID, DCCA_NOMBRE) VALUES (11,'AUTORIDADES MILITARES')
 INTO DCCAT_CATEGORIAS (DCCA_ID, DCCA_NOMBRE) VALUES (12,'VARIOS')
SELECT * FROM DUAL;

-- ===============================
-- CATALOGO DE SUBCATEGORÍAS
-- ===============================
INSERT ALL
-- ARMA
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (1,'Infantería', 1)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (2,'Caballería', 1)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (3,'Artillería', 1)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (4,'Ingeniería', 1)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (5,'Comunicaciones', 1)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (6,'Inteligencia', 1)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (7,'Aviación del Ejército', 1)

-- SERVICIO
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (8,'Intendencia', 2)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (9,'Material de guerra', 2)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (10,'Transportes', 2)

-- ESPECIALISTA
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (11,'Sanidad', 3)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (12,'Administración general', 3)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (13,'Músicos', 3)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (14,'Veterinaria', 3)

-- VARIOS
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (15,'Ejército', 4)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (16,'Fuerzas especiales', 4)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (17,'SIS', 4)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (18,'Personal', 4)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (19,'Otros', 4)

-- ÚNICAS
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (20,'ÚNICA DOCTRINA MILITAR CONJUNTA', 5)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (21,'ÚNICA LITERATURA MILITAR', 6)
 INTO DMSUB_SUBCATEGORIAS (DMSB_ID, DMSB_NOMBRE, DCCAT_CATEGORIAS_DCCA_ID) VALUES (22,'ÚNICA DOCUMENTOS DE INVESTIGACIÓN', 7)
SELECT * FROM DUAL;

-- ===============================
-- CATALOGO DE TIPOS
-- ===============================
INSERT ALL
 INTO DMTYP_TIPOS (DMTY_ID, DMTY_CODIGO, DMTY_NOMBRE_TIPO, DMTY_ESTADO) VALUES (1, 1,'MANUALES FUNDAMENTALES DEL EJÉRCITO',1)
 INTO DMTYP_TIPOS (DMTY_ID, DMTY_CODIGO, DMTY_NOMBRE_TIPO, DMTY_ESTADO) VALUES (2, 2,'MANUALES FUNDAMENTALES DE REFERENCIA DEL EJÉRCITO',1)
 INTO DMTYP_TIPOS (DMTY_ID, DMTY_CODIGO, DMTY_NOMBRE_TIPO, DMTY_ESTADO) VALUES (3, 3,'MANUALES DE CAMPAÑA DEL EJÉRCITO',1)
 INTO DMTYP_TIPOS (DMTY_ID, DMTY_CODIGO, DMTY_NOMBRE_TIPO, DMTY_ESTADO) VALUES (4, 4,'MANUALES DE TÉCNICAS DEL EJÉRCITO',1)
 INTO DMTYP_TIPOS (DMTY_ID, DMTY_CODIGO, DMTY_NOMBRE_TIPO, DMTY_ESTADO) VALUES (5, 5,'SIN TIPO',1)
SELECT * FROM DUAL;

-- ===============================
-- CATALOGO DE GRUPOS
-- ===============================
INSERT ALL
 INTO DMGRP_GRUPOS (DMGRP_ID, DMGRP_CODIGO, DMGRP_ESTADO, DMGRP_NOMBRE) VALUES (1, 1, 1, 'DOCTRINA MILITAR CONJUNTA')
 INTO DMGRP_GRUPOS (DMGRP_ID, DMGRP_CODIGO, DMGRP_ESTADO, DMGRP_NOMBRE) VALUES (2, 2, 1, 'DOCTRINA MILITAR EJÉRCITO')
 INTO DMGRP_GRUPOS (DMGRP_ID, DMGRP_CODIGO, DMGRP_ESTADO, DMGRP_NOMBRE) VALUES (3, 3, 1, 'PUBLICACIONES MILITARES DE GESTIÓN INSTITUCIONAL')
 INTO DMGRP_GRUPOS (DMGRP_ID, DMGRP_CODIGO, DMGRP_ESTADO, DMGRP_NOMBRE) VALUES (4, 4, 1, 'LEYES Y REGLAMENTOS MILITARES')
 INTO DMGRP_GRUPOS (DMGRP_ID, DMGRP_CODIGO, DMGRP_ESTADO, DMGRP_NOMBRE) VALUES (5, 5, 1, 'HISTORIA MILITAR')
 INTO DMGRP_GRUPOS (DMGRP_ID, DMGRP_CODIGO, DMGRP_ESTADO, DMGRP_NOMBRE) VALUES (6, 6, 1, 'LITERATURA MILITAR')
 INTO DMGRP_GRUPOS (DMGRP_ID, DMGRP_CODIGO, DMGRP_ESTADO, DMGRP_NOMBRE) VALUES (7, 7, 1, 'DOCUMENTOS DE INVESTIGACIÓN')
SELECT * FROM DUAL;

-- ===============================
-- RELACIÓN GRUPO-CATEGORÍA
-- ===============================
INSERT ALL
 INTO DMGRP_CAT (DMGC_ID, DMGC_GRUPO_ID, DMGC_CATEGORIA_ID) VALUES (1, 2, 1)
 INTO DMGRP_CAT (DMGC_ID, DMGC_GRUPO_ID, DMGC_CATEGORIA_ID) VALUES (2, 2, 2)
 INTO DMGRP_CAT (DMGC_ID, DMGC_GRUPO_ID, DMGC_CATEGORIA_ID) VALUES (3, 2, 3)
 INTO DMGRP_CAT (DMGC_ID, DMGC_GRUPO_ID, DMGC_CATEGORIA_ID) VALUES (4, 2, 4)
 INTO DMGRP_CAT (DMGC_ID, DMGC_GRUPO_ID, DMGC_CATEGORIA_ID) VALUES (5, 1, 5)
 INTO DMGRP_CAT (DMGC_ID, DMGC_GRUPO_ID, DMGC_CATEGORIA_ID) VALUES (6, 6, 6)
 INTO DMGRP_CAT (DMGC_ID, DMGC_GRUPO_ID, DMGC_CATEGORIA_ID) VALUES (7, 7, 7)
 INTO DMGRP_CAT (DMGC_ID, DMGC_GRUPO_ID, DMGC_CATEGORIA_ID) VALUES (8, 4, 8)
 INTO DMGRP_CAT (DMGC_ID, DMGC_GRUPO_ID, DMGC_CATEGORIA_ID) VALUES (9, 4, 9)
 INTO DMGRP_CAT (DMGC_ID, DMGC_GRUPO_ID, DMGC_CATEGORIA_ID) VALUES (10, 5, 10)
 INTO DMGRP_CAT (DMGC_ID, DMGC_GRUPO_ID, DMGC_CATEGORIA_ID) VALUES (11, 5, 11)
 INTO DMGRP_CAT (DMGC_ID, DMGC_GRUPO_ID, DMGC_CATEGORIA_ID) VALUES (12, 5, 12)
SELECT * FROM DUAL;
